# Generated by Django 5.2.9 on 2026-07-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='thread',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
